import { runMigrations } from "stripe-replit-sync";
import { getStripeSync } from "./lib/stripeClient";
import { db } from "@workspace/db";
import { sql } from "drizzle-orm";
import app from "./app";
import { logger } from "./lib/logger";
import { readFile, access } from "node:fs/promises";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __serverDir = dirname(fileURLToPath(import.meta.url));

// ── DB migrations ────────────────────────────────────────────────────────────
async function runAppMigrations() {
  // Stripe schema
  const databaseUrl = process.env.DATABASE_URL!;
  await runMigrations({ databaseUrl, schema: "stripe" });

  // Application tables
  await db.execute(sql`
    CREATE TABLE IF NOT EXISTS users (
      id                TEXT        PRIMARY KEY,
      email             TEXT,
      stripe_customer_id TEXT,
      has_access_code   BOOLEAN     NOT NULL DEFAULT FALSE,
      created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);
  // Idempotent: add columns to existing tables that were created before these fields
  await db.execute(sql`
    ALTER TABLE users ADD COLUMN IF NOT EXISTS has_access_code BOOLEAN NOT NULL DEFAULT FALSE
  `);
  // Per-student session invalidation: updated on PIN reset to block previously issued JWTs
  await db.execute(sql`
    ALTER TABLE users ADD COLUMN IF NOT EXISTS session_valid_after TIMESTAMPTZ
  `);
  await db.execute(sql`
    ALTER TABLE users ADD COLUMN IF NOT EXISTS story_credits INTEGER NOT NULL DEFAULT 0
  `);

  await db.execute(sql`
    CREATE TABLE IF NOT EXISTS print_orders (
      id                        SERIAL      PRIMARY KEY,
      user_id                   TEXT        NOT NULL,
      story_id                  INTEGER,
      stripe_session_id         TEXT,
      stripe_payment_intent_id  TEXT,
      customer_email            TEXT,
      customer_name             TEXT,
      shipping_address          JSONB       NOT NULL,
      lulu_job_id               TEXT,
      quantity                  INTEGER     NOT NULL DEFAULT 1,
      amount_cents              INTEGER,
      currency                  TEXT        DEFAULT 'usd',
      status                    TEXT        NOT NULL DEFAULT 'pending_payment',
      created_at                TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at                TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);

  // Add user_id column to stories if it doesn't exist yet
  await db.execute(sql`
    ALTER TABLE stories ADD COLUMN IF NOT EXISTS user_id TEXT
  `);

  // Reference photos — base64 image store (replaces GCS for user-uploaded reference images)
  await db.execute(sql`
    CREATE TABLE IF NOT EXISTS reference_photos (
      id   TEXT PRIMARY KEY,
      data TEXT NOT NULL
    )
  `);
  // Idempotent: add data_url column if table was created in an earlier session without it
  await db.execute(sql`
    ALTER TABLE reference_photos ADD COLUMN IF NOT EXISTS data_url TEXT NOT NULL DEFAULT ''
  `);

  // Soft-delete: stories are hidden from owner but share links remain valid
  await db.execute(sql`
    ALTER TABLE stories ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ
  `);

  // Gift card access: time-limited unlimited access granted by gift card redemption
  await db.execute(sql`
    ALTER TABLE users ADD COLUMN IF NOT EXISTS gift_access_expires_at TIMESTAMPTZ
  `);

  // Print credits: granted by printed book gift card redemption
  await db.execute(sql`
    ALTER TABLE users ADD COLUMN IF NOT EXISTS print_credits INTEGER NOT NULL DEFAULT 0
  `);

  // Gift card codes: generated by webhook, redeemed by recipients
  await db.execute(sql`
    CREATE TABLE IF NOT EXISTS gift_card_codes (
      code                  TEXT        PRIMARY KEY,
      tier                  TEXT        NOT NULL,
      stripe_session_id     TEXT,
      buyer_email           TEXT,
      redeemed_at           TIMESTAMPTZ,
      redeemed_by_user_id   TEXT,
      created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);

  // Lulu submission error tracking — stores last error message for failed/stuck print orders
  await db.execute(sql`
    ALTER TABLE print_orders ADD COLUMN IF NOT EXISTS lulu_last_error TEXT
  `);

  // School Mode — parental/teacher control for classroom-safe content generation
  await db.execute(sql`
    ALTER TABLE users ADD COLUMN IF NOT EXISTS school_mode BOOLEAN NOT NULL DEFAULT FALSE
  `);
  await db.execute(sql`
    ALTER TABLE users ADD COLUMN IF NOT EXISTS school_mode_pin TEXT
  `);

  // ── Classroom roster feature ────────────────────────────────────────────────
  await db.execute(sql`
    CREATE TABLE IF NOT EXISTS classes (
      id          SERIAL      PRIMARY KEY,
      teacher_id  TEXT        NOT NULL,
      class_name  TEXT        NOT NULL,
      class_code  TEXT        NOT NULL UNIQUE,
      created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);
  // Student fields on the shared users table
  await db.execute(sql`ALTER TABLE users ADD COLUMN IF NOT EXISTS is_student BOOLEAN NOT NULL DEFAULT FALSE`);
  await db.execute(sql`ALTER TABLE users ADD COLUMN IF NOT EXISTS class_id INTEGER`);
  await db.execute(sql`ALTER TABLE users ADD COLUMN IF NOT EXISTS first_name TEXT`);
  await db.execute(sql`ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar TEXT`);
  await db.execute(sql`ALTER TABLE users ADD COLUMN IF NOT EXISTS pin TEXT`);
  await db.execute(sql`ALTER TABLE users ADD COLUMN IF NOT EXISTS classroom_enabled BOOLEAN NOT NULL DEFAULT FALSE`);
  await db.execute(sql`ALTER TABLE users ADD COLUMN IF NOT EXISTS school_code_id INTEGER`);
  await db.execute(sql`ALTER TABLE classes ADD COLUMN IF NOT EXISTS announcement_message TEXT`);
  await db.execute(sql`ALTER TABLE classes ADD COLUMN IF NOT EXISTS value_of_week TEXT`);
  await db.execute(sql`ALTER TABLE classes ADD COLUMN IF NOT EXISTS sight_words TEXT`);
  await db.execute(sql`ALTER TABLE classes ADD COLUMN IF NOT EXISTS assignment_due_date DATE`);
  await db.execute(sql`ALTER TABLE classes ADD COLUMN IF NOT EXISTS announcement_updated_at TIMESTAMPTZ`);
  await db.execute(sql`ALTER TABLE users ADD COLUMN IF NOT EXISTS points INTEGER NOT NULL DEFAULT 0`);
  await db.execute(sql`ALTER TABLE stories ADD COLUMN IF NOT EXISTS submitted_by_student_id TEXT`);
  await db.execute(sql`ALTER TABLE stories ADD COLUMN IF NOT EXISTS story_status TEXT NOT NULL DEFAULT 'teacher'`);
  await db.execute(sql`ALTER TABLE classes ADD COLUMN IF NOT EXISTS point_value_per_sight_word INTEGER NOT NULL DEFAULT 1`);
  await db.execute(sql`ALTER TABLE classes ADD COLUMN IF NOT EXISTS points_for_published INTEGER NOT NULL DEFAULT 5`);
  await db.execute(sql`ALTER TABLE users ADD COLUMN IF NOT EXISTS full_name TEXT`);
  await db.execute(sql`
    CREATE TABLE IF NOT EXISTS announcement_history (
      id                       SERIAL PRIMARY KEY,
      class_id                 INTEGER NOT NULL,
      message                  TEXT,
      value_of_week            TEXT,
      sight_words              TEXT,
      assignment_due_date      DATE,
      point_value_per_sight_word INTEGER NOT NULL DEFAULT 1,
      points_for_published     INTEGER NOT NULL DEFAULT 5,
      posted_at                TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);
  await db.execute(sql`
    CREATE TABLE IF NOT EXISTS parent_links (
      id            SERIAL PRIMARY KEY,
      parent_user_id TEXT NOT NULL,
      student_id     TEXT NOT NULL,
      class_id       INTEGER NOT NULL,
      created_at     TIMESTAMPTZ DEFAULT NOW(),
      UNIQUE(parent_user_id, student_id)
    )
  `);
  await db.execute(sql`
    CREATE TABLE IF NOT EXISTS school_access_codes (
      id          SERIAL      PRIMARY KEY,
      code        TEXT        NOT NULL UNIQUE,
      school_name TEXT        NOT NULL,
      is_active   BOOLEAN     NOT NULL DEFAULT TRUE,
      created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);

  // ── Story reading + exercises feature ───────────────────────────────────────
  // Track which student has read which story (points awarded once per story)
  await db.execute(sql`
    CREATE TABLE IF NOT EXISTS story_reads (
      id         SERIAL      PRIMARY KEY,
      student_id TEXT        NOT NULL,
      story_id   INTEGER     NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      UNIQUE(student_id, story_id)
    )
  `);
  // Cache AI-generated exercises per story
  await db.execute(sql`
    CREATE TABLE IF NOT EXISTS story_exercises (
      id             SERIAL      PRIMARY KEY,
      story_id       INTEGER     NOT NULL UNIQUE,
      exercises_json TEXT        NOT NULL,
      created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);
  // Track which students completed which exercise types (points awarded once)
  await db.execute(sql`
    CREATE TABLE IF NOT EXISTS exercise_completions (
      id             SERIAL      PRIMARY KEY,
      student_id     TEXT        NOT NULL,
      story_id       INTEGER     NOT NULL,
      exercise_type  TEXT        NOT NULL,
      points_awarded INTEGER     NOT NULL DEFAULT 0,
      created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      UNIQUE(student_id, story_id, exercise_type)
    )
  `);
  // ── Family Hub feature ──────────────────────────────────────────────────────
  await db.execute(sql`ALTER TABLE classes ADD COLUMN IF NOT EXISTS is_family_hub BOOLEAN NOT NULL DEFAULT FALSE`);
  await db.execute(sql`ALTER TABLE users ADD COLUMN IF NOT EXISTS family_hub_enabled BOOLEAN NOT NULL DEFAULT FALSE`);

  // Avatar bank — pre-seeded character illustrations for story art
  await db.execute(sql`
    CREATE TABLE IF NOT EXISTS avatar_bank (
      id         TEXT        PRIMARY KEY,
      name       TEXT        NOT NULL,
      category   TEXT        NOT NULL,
      emoji      TEXT        NOT NULL DEFAULT '',
      sort_order INTEGER     NOT NULL DEFAULT 0,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);

  // Seed avatar images if the bank is empty (runs in both dev and prod on startup)
  const avatarCount = await db.execute(sql`SELECT COUNT(*) AS n FROM avatar_bank`);
  if (Number((avatarCount.rows[0] as any).n) === 0) {
    const AVATARS = [
      { id: "avatar_kid_001",       name: "Amara",           category: "kids",      emoji: "👧🏿" },
      { id: "avatar_kid_002",       name: "Liam",            category: "kids",      emoji: "👦🏼" },
      { id: "avatar_kid_003",       name: "Sofia",           category: "kids",      emoji: "👧🏽" },
      { id: "avatar_kid_004",       name: "Kai",             category: "kids",      emoji: "👦🏻" },
      { id: "avatar_kid_005",       name: "Maya",            category: "kids",      emoji: "👧🏾" },
      { id: "avatar_kid_006",       name: "Marcus",          category: "kids",      emoji: "👦🏿" },
      { id: "avatar_animal_001",    name: "Leo the Lion",    category: "animals",   emoji: "🦁" },
      { id: "avatar_animal_002",    name: "Benny the Bunny", category: "animals",   emoji: "🐰" },
      { id: "avatar_animal_003",    name: "Fiona the Fox",   category: "animals",   emoji: "🦊" },
      { id: "avatar_animal_004",    name: "Drake the Dragon",category: "animals",   emoji: "🐉" },
      { id: "avatar_animal_005",    name: "Buddy the Dog",   category: "animals",   emoji: "🐶" },
      { id: "avatar_adventure_001", name: "Astronaut",       category: "adventure", emoji: "🚀" },
      { id: "avatar_adventure_002", name: "Superhero",       category: "adventure", emoji: "🦸" },
      { id: "avatar_adventure_003", name: "Explorer",        category: "adventure", emoji: "🧭" },
      { id: "avatar_adventure_004", name: "Knight",          category: "adventure", emoji: "⚔️" },
      { id: "avatar_career_001",    name: "Doctor",          category: "careers",   emoji: "👨‍⚕️" },
      { id: "avatar_career_002",    name: "Police Officer",  category: "careers",   emoji: "👮" },
      { id: "avatar_career_003",    name: "Veterinarian",    category: "careers",   emoji: "🐾" },
      { id: "avatar_career_004",    name: "Mechanic",        category: "careers",   emoji: "🔧" },
      { id: "avatar_career_005",    name: "Firefighter",     category: "careers",   emoji: "🚒" },
    ];
    // Avatar PNGs are copied into dist/avatars/ during the build step (see build.mjs).
    // Fall back to the workspace source path for local dev runs that skip the build.
    const distAvatars = resolve(__serverDir, "avatars");
    const srcAvatars = resolve(__serverDir, "../../attached_assets/avatars");
    const avatarDir = await access(distAvatars).then(() => distAvatars).catch(() => srcAvatars);
    let seeded = 0;
    for (const [i, a] of AVATARS.entries()) {
      try {
        const imgPath = resolve(avatarDir, `${a.id}.png`);
        await access(imgPath); // throws if missing — skip silently
        const buf = await readFile(imgPath);
        const dataUrl = `data:image/png;base64,${buf.toString("base64")}`;
        await db.execute(sql`
          INSERT INTO reference_photos (id, data_url) VALUES (${a.id}, ${dataUrl})
          ON CONFLICT (id) DO UPDATE SET data_url = EXCLUDED.data_url
        `);
        await db.execute(sql`
          INSERT INTO avatar_bank (id, name, category, emoji, sort_order)
          VALUES (${a.id}, ${a.name}, ${a.category}, ${a.emoji}, ${i})
          ON CONFLICT (id) DO UPDATE SET
            name=EXCLUDED.name, category=EXCLUDED.category,
            emoji=EXCLUDED.emoji, sort_order=EXCLUDED.sort_order
        `);
        seeded++;
      } catch {
        // Missing file or DB error — skip this avatar
      }
    }
    if (seeded > 0) logger.info({ seeded }, "Avatar bank seeded");
  }
}

// ── Stripe init ──────────────────────────────────────────────────────────────
async function initStripe() {
  try {
    const stripeSync = await getStripeSync();

    const webhookBaseUrl = `https://${process.env.REPLIT_DOMAINS?.split(",")[0]}`;
    await stripeSync.findOrCreateManagedWebhook(`${webhookBaseUrl}/api/stripe/webhook`);
    logger.info("Stripe webhook configured");

    stripeSync.syncBackfill().catch((err) => {
      logger.error({ err }, "Stripe backfill error");
    });
  } catch (err) {
    logger.error({ err }, "Stripe init failed — continuing without Stripe");
  }
}

// ── Start ────────────────────────────────────────────────────────────────────
const rawPort = process.env["PORT"];
if (!rawPort) throw new Error("PORT environment variable is required");
const port = Number(rawPort);
if (Number.isNaN(port) || port <= 0) throw new Error(`Invalid PORT: "${rawPort}"`);

await runAppMigrations();
await initStripe();

// Start background Lulu status poller — alerts owner on rejected orders
const { startLuluStatusPoller } = await import("./lib/luluService");
startLuluStatusPoller();

app.listen(port, (err) => {
  if (err) {
    logger.error({ err }, "Error listening on port");
    process.exit(1);
  }
  logger.info({ port }, "Server listening");
});
